{{- range $name, $svc := .Values.microservices }}
{{- if $svc.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "gaz.labels" $ | nindent 4 }}
    {{- include "gaz.selectorLabels" $name | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "gaz.selectorLabels" $name | nindent 4 }}
  ports:
    - name: http
      port: {{ $svc.port }}
      targetPort: {{ $svc.port }}
      protocol: TCP
{{- end }}
{{- end }}
